-- apply changes
create table server_real_time (
  id                            bigint generated by default as identity not null,
  last_crash_date               timestamp,
  last_start_date               timestamp,
  status                        integer not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint ck_server_real_time_status check ( status in (0,1,2)),
  constraint pk_server_real_time primary key (id)
);

