-- apply changes
create table server_statistics (
  id                            bigint generated by default as identity not null,
  server_id                     bigint not null,
  type                          integer not null,
  time                          bigint not null,
  value                         double not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint ck_server_statistics_type check ( type in (0,1,2,3,4,5,6,7)),
  constraint pk_server_statistics primary key (id)
);

alter table server add column container_port integer default 25565 not null;
alter table server add column host_port integer default 25565 not null;

