# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release CI

on:
  workflow_dispatch:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: chmod +x gradlew
      - run: ./gradlew installDist

      - name: Upload Files
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "build/libs/emss-backend-all.jar"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "~/emss/"

      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            source /etc/profile
            cd ~/emss/run
            ./apprun.sh stop emss-backend-all.jar
            mv ../emss-backend-all.jar ./
            ./apprun.sh start emss-backend-all.jar
